# Makefile by Richard_Chen 2016/09/02
# Format shown below,
#	target_you_want:dependency files
#	(TAB without expand)commands

#Variable defines here
CC = g++
CFLAGS = -g -Wall -ansi

#Main makefile logic
all:hello.cpp
	$(CC) hello.cpp -o hello.out
clean:
	$(RM) *.out
